### ISSUE TITLE
History of Code for America

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/tracker#18]
@alexandralphillips 

This is envisioned as a blog post/member doc.  It is reasonable to attempt to educate ourselves, organization members, and members of the community on the parent organization that we are all apart of.

**Comment by neolytics** [comment]
So this had been completed and needs to be added to the website. I think this should be its own pager on the website. I'm going to add the issue there and close this.

**Comment by jbrooks036** [comment]
Cool!  So can you / Alex provide a pointer to where it is?  I'd love to see
it.

Great work, Alex!

~JoAnn

**Comment by neolytics** [comment]
https://docs.google.com/a/nextgxdx.com/document/d/15fbH_hvsVfoSued7_Z8feWz7kamJF6v_bUpdSFDIeMw/edit

Let me know if that link doesn't work.  It's shared with the codefornashville at gmail account.

**Comment by jbrooks036** [comment]
Excellent!  Thanks.

j.

**Comment by jbrooks036** [comment]
I'm not sure this is a "tracker" kind of thing, but thought you all might
appreciate it and couldn't find a more general purpose email list for C4N
members...

Can we get a note about it, &/or link to it on our website?

~JoAnn


---------- Forwarded message ----------
From: Evan Mackinder, Sunlight Foundation <info@sunlightfoundation.com>
Date: Fri, Feb 13, 2015 at 8:47 AM
Subject: A huge win for opengov!
To: jbrooks@umich.edu


         The Sunlight Foundation is a nonpartisan nonprofit that advocates
for open government globally and uses technology to make government more
accountable to all.  View on the web
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=3HOOnKwBtnUQZExqNEwqAWkKIgii%2Bd6Y>
| Join us
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=DGGXozR0UhJwRUtpYyyEP2kKIgii%2Bd6Y>
Follow Us: [image: twitter]
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=2gt0YjpOsJ9kvh1f0pEZHWkKIgii%2Bd6Y>
[image:
facebook]
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=j6Oc3g%2BOGps%2BJMII7d499WkKIgii%2Bd6Y>
              [image:
Sunlight Foundation]
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=nFLV2mHIc%2B87Zx%2Fs6q%2BYPGkKIgii%2Bd6Y>
------------------------------
       » An unprecedented look at government data holdings
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=TeoROJwYqqHOf2%2Bj0sMW1GkKIgii%2Bd6Y>
 «
------------------------------

Supporter,

We’ve got some really exciting news to share about the future of open data:
*The* *United States government has finally agreed to release what is
likely the largest index of government data in the world.*
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=Rn2QEpPDqfwxdkFGI5qGRmkKIgii%2Bd6Y>

This index is something we’ve been fighting for years. *We’ve long sought
to create a more complete picture of the government’s data holdings*, and
getting this index out in the open is a big step toward a more open and
accountable government.

It didn’t come easy. The news of the release comes in *response to a
Freedom of Information Act request we filed 14 months ago
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=ioD2p5wXwU41EHmBFdM7zWkKIgii%2Bd6Y>*
with the Office of Management and Budget. We were even prepared to go to
court when it appeared that the agency would withhold the index.

*But we’re happy to say that it won’t come to that. Now, for the first
time, we’re going to find out just how much data is in the hands of the
government. Click here to read our blog post. *
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=nDRKWVr2eGX02l9AzudnI2kKIgii%2Bd6Y>

This is a win for Sunlight, but it’s also a win for the community. This
week, we’re celebrating along with our friends, allies and, of course, you.

As always, we’ll keep you updated with any further news about the index.
But until then: high fives all around!

Onward,

Evan, Matt, Sean and the Sunlight team

P.S. It's thanks to supporters like you that we're able to continue our
open data work. You can pitch in to support these efforts by making a
contribution today (and thanks!)
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=j6Oc3g%2BOGpsiaO0gKRWQD2kKIgii%2Bd6Y>
.
             Mission Statement

The Sunlight Foundation is a nonpartisan nonprofit that advocates for open
government globally and uses technology to make government more accountable
to all.
------------------------------
We value your input and suggestions!

Let us hear from you at sunlightfoundation.com/contact
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=o%2ByXAE8RKCrMCebt0zt50u0X4u51nCn7>
or call us at 202-742-1520.
1818 N Street NW | Suite 300 | Washington, DC 20036

The Sunlight Foundation does not rent or sell email lists. Read about
our Privacy
Policy.
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=zKbMtztygPtflyrva1JO0WkKIgii%2Bd6Y>
------------------------------

Unsubscribe or manage your email preferences list
<http://salsa4.salsalabs.com/dia/track.jsp?v=2&c=2eoFcs5jogp%2FXZjs5QXMxWkKIgii%2Bd6Y>
         [image: empowered by Salsa] <http://www.salsalabs.com/?email>
