### ISSUE TITLE
CodeAcross 2015 Blog Series

### ISSUE THREAD

**Issue by alexandralphillips** [code-for-nashville/tracker#25]
@jchapin @erinpagemd @jbrooks036 @beck410 @neolytics @jcockhren @sciurus @JamesNix 

I previously brought up the idea to post a blog series on our website leading up to CodeAcross that corresponds to this years theme: Principles for 21st Century Government. There are 7 principles that CfA outlines on their websites, and next week there will be 7 weeks until the event. We can do one blog post per week, and this will be a great way to create content for our website and create a good lead-up to the event.
Some people had expressed interest in volunteering to write a blog post, so I'll list them all below, and if you would like to claim one just respond with the one you'd like to do. These blogs do not have to be extensive, they can just be simple posts discussing the principle and how it relates to your own experiences, ideas, goals or our community's needs. Thanks!

1. Design for people's needs - Due 1/5/15
2. Make it easy for everyone to participate - Due 1/12/15
3. Focus on what government can do - Due 1/19/15
4. Make data easy to find and use - Due 1/26/14
5. Use data to make and improve decisions - Due 2/2/15
6. Choose the right technology for the job - Due 2/9/15
7. Organize for results - Due 2/16/15

Reference http://www.codeforamerica.org/governments/principles/ for the list and to read what CfA has written about the principle to get you going.

**Comment by erinpagemd** [comment]
I will take #3.

**Comment by jcockhren** [comment]
I'll do #6

**Comment by neolytics** [comment]
I'll do number 5

**Comment by erinpagemd** [comment]
@beck410 is doing #4

**Comment by erinpagemd** [comment]
We need to get a standard process down for submitting these blogs. Let's make it easier to get others to participate!

**Comment by neolytics** [comment]
@beck410 @sciurus @erinpagemd 

I agree whole heartedly on this, and was alluding to exactly this issue in the "Make it easier for everyone to participate" post.  Now that we at least in theory have AWS credentials I think a second iteration of the website may be warranted, one that has a blogging engine with user authentication etc.

**Comment by beck410** [comment]
for now you can send me the blog post and i'll upload to the website

**Comment by erinpagemd** [comment]
@beck410 I don't know how else to do this!::

https://gist.github.com/erinpagemd/24a6270fb8f56be67582

:sos:

**Comment by beck410** [comment]
no prob i'll upload it tonight and back date it so the blog post dates aren't too close

**Comment by Brenntron** [comment]
I'll take 7!

**Comment by erinpagemd** [comment]
all of the blogs are claimed! Good job guys!

**Comment by erinpagemd** [comment]
@beck410 Hey ! We have a judge announcement. Can you get it out asap? It is super short.

https://gist.github.com/erinpagemd/776a8efb469ce2a598c4

**Comment by beck410** [comment]
i'll put it up during lunch :)

**Comment by erinpagemd** [comment]
@beck410 you are the best. :smile:

**Comment by neolytics** [comment]
I still plan on writing number 5, I want it to coincide with the release of Inclucivics.  Just because code across is over doesn't mean the principles don't still apply.

**Comment by jchapin** [comment]
Event done, closing the issue.
