### ISSUE TITLE
Code Across 2015

### ISSUE THREAD

**Issue by erinpagemd** [code-for-nashville/tracker#26]

**Comment by erinpagemd** [comment]
Notes from Planning Meeting on 1/20/2015:
==================================

* We are confirming judges and will make an announcement next week.
* Meetings will continue on Tuesdays at 6pm at the E-spaces in Belle Meade.
* We need a process for getting blogs for the series submitted.
* Sending out messages about the following on Twitter and Facebook
  * next meeting
  * codeAcross
  * blog series
  * ask for volunteers
* Judging will be as follows:
 * from 5-7pm on Sunday judges will review a science fair of projects
 * points from the judges will be calculated
 * the groups with the top 3 scores will present their projects to the audience
 * audience chooses winner by round of applause
* Tentative Schedule:
  * Friday: 6-7pm Meet and Greet, 7-10p Share ideas and form teams.
  * Saturday: All day hacking. Lunch for registered participants.
  * Sunday: Hacking until 5pm. Presentations for finalists at 7pm.
* Judges will be needed 4-8pm
* We need swag for participants, finalists, and winners!
* Call for volunteers
* Print:
  * Judge score cards
  * Signage for registration desk 
* Checks for donations can be made to Code for Nashville
* We need 2 more quotes on box lunches
* Meals:
  * Food Truck options?
  * Saturday Lunch
  * Coffee, tea, soda, light snack?
* Volunteer activities
  * registration table
  * coffee service
  * lunch service
  * judge concierge
  * clean up
  * set-up?
  * food pick up
  * volunteer concierge
  * swag?
* Multicity Innovation Campaign
* Budget
* Audio/Visual
* Expecting approximately 50 participants (8 - 10 teams)
* Survival Guide

**Comment by beck410** [comment]
in regards to food trucks i have music city pie co, bao down and dawg daze interested in both nights. i think two trucks will be enough

I told them 50-80 people would attend and 30-50 will probably want food. Do these estimates look right?

**Comment by erinpagemd** [comment]
@beck410 Looks right to me!

**Comment by Deanna2000** [comment]
Hey guys! Is 50-80 the number we are using when asking for swag donations? Just to confirm, we have no restrictions for people giving us swag, right? Other events require companies to be a sponsor in order to give out swag but I understand that is not a limitation for us.

**Comment by jchapin** [comment]
@Deanna2000, That's a good number, and they should keep in mind the tam size might vary. No restrictions on donations. We just cannot explicitly promise exposure in exchange for any donations.

**Comment by Deanna2000** [comment]
Awesome, Thanks!

**Comment by beck410** [comment]
Food Trucks Update: Music City Pie co and Dawg Days are booked for both nights 6-8pm

**Comment by erinpagemd** [comment]
@beck410 Perfect! Thank you. We may just need to send a reminder message closer to the date.

**Comment by beck410** [comment]
I told them i'd update them on estimated numbers a few days out from the event

**Comment by beck410** [comment]
@erinpagemd  @alexandralphillips @jchapin Dave finished the design for the poster - i didn't know where else to put it so i added it to the google docs https://drive.google.com/?usp=folder&authuser=0#folders/0Bzo3uuYNgN29ajc1SVRfazN6aEk - let me know what else needs to be added or if it needs to be in another format

**Comment by erinpagemd** [comment]
nice! now we must decide on printing size. i think we just wanted to get one??

**Comment by beck410** [comment]
I vaguely remember 8x10 being recommended as a good size by someone at the last management meeting

**Comment by jchapin** [comment]
I'd be happy to use my allotment of color copies to print up 50 tomorrow night.

**Comment by beck410** [comment]
So bit of bad luck with the food trucks - the two original food trucks had to pull out due to the weather - rang around and same response as the other trucks - so i was thinking what if we gave everyone who wants dinner the option to put in $10 to deliver a range of pizzas or some other delivery?

**Comment by jchapin** [comment]
I think that's reasonable.
