### ISSUE TITLE
Nashville Recycle Locations page???

### ISSUE THREAD

**Issue by erinpagemd** [code-for-nashville/tracker#28]
Guys! I was practicing stuff from software school and used Nashville's open data portal to make a website for Nashville Recycle Locations. It needs a CSS framework, but I thought we might want to use it. 

Just a thought.

https://github.com/erinpagemd/nash-recycle-centers

**Comment by neolytics** [comment]
Seems appropriate for nashviva no? Nice work.

Jon Staples, M.S.2
Data Scientist
NextGxDx

Email: jonstaples@hargray.com
Phone: 803-272-8073
Twitter: @techneolytics
