### ISSUE TITLE
Open management meeting notes

### ISSUE THREAD

**Issue by beck410** [code-for-nashville/tracker#29]
@neolytics 

Could you point me in the direction of the last open management meeting notes? Couldn't find them on Google Docs. Looking to get to work on the current projects page :smile:

**Comment by neolytics** [comment]
Uploaded,

https://docs.google.com/a/nextgxdx.com/document/d/1ICVNn0qXr5LgOIPF1MpdYzcMYAW1U4QL9SVDMu1ZkCI/edit

On Thu, Feb 5, 2015 at 9:58 PM, Rebecca Cronin-Dixon <
notifications@github.com> wrote:

> @neolytics <https://github.com/neolytics>
>
> Could you point me in the direction of the last open management meeting
> notes? Couldn't find them on Google Docs. Looking to get to work on the
> current projects page [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/code-for-nashville/tracker/issues/29>.
>



-- 
Jon Staples M.S.2

[Data Scientist | NextGxDx | www.nextgxdx.com]
