### ISSUE TITLE
Distribute remaining credentials to more members

### ISSUE THREAD

**Issue by sciurus** [code-for-nashville/tracker#7]
According to our [November notes](https://github.com/code-for-nashville/tracker/wiki/November-2014-Management-Meeting):

> Some account access/management still needs to be distributed among members (Google Analytics, Google Group, Zoho mailserver, etc)

**Comment by neolytics** [comment]
@jcockhren Now has credentials

**Comment by jchapin** [comment]
@jcockhren, @neolytics and myself have them. Closing this issue.
